import { useState, useEffect, useContext } from 'react';
import axios from 'axios';
import { AuthContext } from '../context/AuthContext';
import { History, Calendar, Award, AlertTriangle, CheckCircle, ShieldAlert } from 'lucide-react';

const OpportunityHistory = () => {
  const { user } = useContext(AuthContext);
  const [history, setHistory] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchHistory = async () => {
      try {
        const { data } = await axios.get('/api/ai/insights/history', {
          headers: { Authorization: `Bearer ${user.token}` }
        });
        setHistory(data);
      } catch (error) {
        console.error('Failed to fetch opportunity history:', error);
      }
      setLoading(false);
    };
    fetchHistory();
  }, [user]);

  const getSeverityColor = (sev) => {
    switch (sev) {
      case 'high': return 'text-red-400 bg-red-500/10 border-red-500/20';
      case 'medium': return 'text-yellow-400 bg-yellow-500/10 border-yellow-500/20';
      default: return 'text-blue-400 bg-blue-500/10 border-blue-500/20';
    }
  };

  const getStatusBadge = (status) => {
    switch (status) {
      case 'actioned':
        return (
          <span className="flex items-center gap-1 text-[10px] font-bold px-2 py-0.5 bg-green-500/10 text-green-400 rounded border border-green-500/20 uppercase">
            <CheckCircle size={10} /> Launched
          </span>
        );
      case 'dismissed':
        return (
          <span className="flex items-center gap-1 text-[10px] font-bold px-2 py-0.5 bg-gray-500/10 text-gray-400 rounded border border-gray-500/20 uppercase">
            <ShieldAlert size={10} /> Dismissed
          </span>
        );
      default:
        return (
          <span className="flex items-center gap-1 text-[10px] font-bold px-2 py-0.5 bg-blue-500/10 text-blue-400 rounded border border-blue-500/20 uppercase">
            <AlertTriangle size={10} /> Pending
          </span>
        );
    }
  };

  return (
    <div className="space-y-8">
      <div>
        <h1 className="text-3xl font-extrabold text-white tracking-tight flex items-center gap-3">
          <History className="text-purple-400" /> Opportunity History
        </h1>
        <p className="text-gray-400 text-sm mt-1">Review historical growth insights generated by the AI Growth Agent</p>
      </div>

      {loading ? (
        <div className="flex justify-center items-center py-20">
          <span className="animate-spin border-2 border-white/20 border-t-white rounded-full w-8 h-8"></span>
        </div>
      ) : history.length === 0 ? (
        <div className="glass-panel p-10 rounded-2xl text-center">
          <p className="text-gray-400 mb-2 font-medium">No historical logs found</p>
          <p className="text-xs text-gray-500 max-w-md mx-auto">
            Use the **Generate AI Insights** button on the Dashboard to record fresh growth options.
          </p>
        </div>
      ) : (
        <div className="space-y-4">
          {history.map((insight) => (
            <div key={insight._id} className="glass-panel p-6 rounded-2xl flex flex-col md:flex-row justify-between items-start md:items-center gap-4 transition-all hover:border-purple-500/20">
              <div className="space-y-2 flex-1">
                <div className="flex flex-wrap items-center gap-2">
                  <span className={`text-[10px] font-bold px-2 py-0.5 rounded border uppercase tracking-wider ${getSeverityColor(insight.severity)}`}>
                    {insight.severity} Severity
                  </span>
                  <span className="text-[10px] font-semibold px-2 py-0.5 bg-purple-500/10 text-purple-300 rounded border border-purple-500/20 uppercase tracking-wider">
                    {insight.type.replace('_', ' ')}
                  </span>
                  {getStatusBadge(insight.status)}
                </div>
                <h3 className="text-lg font-bold text-white leading-snug">{insight.title}</h3>
                <p className="text-gray-300 text-xs leading-relaxed">{insight.description}</p>
                <div className="text-gray-400 text-xs font-semibold">
                  Recommendation: <span className="text-gray-200 font-normal">{insight.recommendation}</span>
                </div>
              </div>

              <div className="flex md:flex-col items-end gap-3 text-right shrink-0 border-t md:border-t-0 border-white/[0.04] pt-3 md:pt-0 w-full md:w-auto">
                <div className="flex items-center gap-1.5 text-gray-500 text-xs">
                  <Calendar size={13} />
                  {new Date(insight.createdAt).toLocaleString()}
                </div>
                <div className="flex items-center gap-1.5 text-xs text-yellow-400 font-semibold bg-yellow-500/10 border border-yellow-500/20 px-2 py-1 rounded-lg">
                  <Award size={13} />
                  Confidence: {Math.round(insight.confidence * 100)}%
                </div>
                {insight.expectedImpact && (
                  <div className="text-xs text-blue-300 font-medium">
                    Est. Increase: <span className="text-white font-bold">{insight.expectedImpact.estimatedIncreasePercentage}</span>
                  </div>
                )}
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
};

export default OpportunityHistory;
